{
  "formatVersion": "1.1",
  "component": {
    "group": "com.firebaseui",
    "module": "firebase-ui-common",
    "version": "8.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-ui-common-8.0.0.aar",
          "url": "firebase-ui-common-8.0.0.aar",
          "size": 6761,
          "sha512": "a8fae36e9913afba5f9ee3ea5951520ff980d8543221ab94c0e73c717240bea3a15d6c9c47e909fad236c1ac3266c51f2edda205113598a99bea6d90788d5218",
          "sha256": "fd41200b0e51584e399ba35db8b6b2e30d1f97555ad4f5330305932444c639ab",
          "sha1": "cdc5c87799ed5c565ebf439f9a0b62441b93da08",
          "md5": "890779456b28ddf0745bc4d0c9dc6d43"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-ui-common-8.0.0.aar",
          "url": "firebase-ui-common-8.0.0.aar",
          "size": 6761,
          "sha512": "a8fae36e9913afba5f9ee3ea5951520ff980d8543221ab94c0e73c717240bea3a15d6c9c47e909fad236c1ac3266c51f2edda205113598a99bea6d90788d5218",
          "sha256": "fd41200b0e51584e399ba35db8b6b2e30d1f97555ad4f5330305932444c639ab",
          "sha1": "cdc5c87799ed5c565ebf439f9a0b62441b93da08",
          "md5": "890779456b28ddf0745bc4d0c9dc6d43"
        }
      ]
    }
  ]
}
